import { useQuery } from '@tanstack/react-query';
import { adminAccessService } from '../services/adminAccessService';

export function useAdminPermissions(uid: string | undefined) {
  const query = useQuery({
    queryKey: ['admin-access', uid],
    queryFn: () => (uid ? adminAccessService.getAdminAccess(uid) : Promise.resolve({
      role: 'member' as const,
      permissions: {
        canAccessAdmin: false,
        canModerateChallenges: false,
        canApproveChallenges: false,
        canRequestChallengeChanges: false,
        canManageExercises: false,
        canCreateExercises: false,
        canEditExercises: false,
        canDeleteExercises: false,
        canImportExercises: false,
        canExportExercises: false,
        canViewExerciseStats: false,
        canManageUsers: false,
        canSuspendUsers: false,
        canManageGroups: false,
        canModerateGroups: false,
        canFeatureGroups: false,
        canViewAnalytics: false,
        canViewUserGrowthAnalytics: false,
        canViewEngagementAnalytics: false,
        canViewRevenueAnalytics: false,
        canManageDonations: false,
        canManageContent: false,
        canManageNotifications: false,
        canManageSettings: false,
        canManageAppSettings: false,
        canManageAdminUsers: false,
        canViewSystemLogs: false,
      },
    })),
    enabled: !!uid,
    staleTime: 5 * 60 * 1000,
  });

  return {
    ...query,
    role: query.data?.role ?? 'member',
    permissions: query.data?.permissions ?? {
      canAccessAdmin: false,
      canModerateChallenges: false,
      canApproveChallenges: false,
      canRequestChallengeChanges: false,
      canManageExercises: false,
      canCreateExercises: false,
      canEditExercises: false,
      canDeleteExercises: false,
      canImportExercises: false,
      canExportExercises: false,
      canViewExerciseStats: false,
      canManageUsers: false,
      canSuspendUsers: false,
      canManageGroups: false,
      canModerateGroups: false,
      canFeatureGroups: false,
      canViewAnalytics: false,
      canViewUserGrowthAnalytics: false,
      canViewEngagementAnalytics: false,
      canViewRevenueAnalytics: false,
      canManageDonations: false,
      canManageContent: false,
      canManageNotifications: false,
      canManageSettings: false,
      canManageAppSettings: false,
      canManageAdminUsers: false,
      canViewSystemLogs: false,
    },
    isAdmin: query.data?.permissions.canAccessAdmin ?? false,
  };
}
